version: "3"
services:
#  app:
#    image: 8ee485e0f99b
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - postgres
#    environment:
##      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
##      - SPRING_DATASOURCE_USERNAME=postgres
##      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ec2-54-74-77-126.eu-west-1.compute.amazonaws.com:5432/dcsmbq2fpdrii6
#      - SPRING_DATASOURCE_USERNAME=smylsoazyxfzul
#      - SPRING_DATASOURCE_PASSWORD=67c97e47621b214134f6a0089a585c309553363f91274c90369030d290985d3e
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - 8080:8080
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

volumes:
  db-data: